insert into Taller(Nombre , Pag_web, Correo) values 
('Taller Alto Orinoco', 'jigsy.com', 'oklaiser0@sphinn.com'),
('Taller Atabapo', 'free.fr', 'nalwen1@liveinternet.ru'),
('Taller Atures', 'prnewswire.com', 'tmoodie2@blogger.com'),
('Taller Autana', 'chron.com', 'bbeckford3@mozilla.com'),
('Taller Manapiare', 'artisteer.com', 'adunstall4@ameblo.jp'),
('Taller Maroa', 'who.int', 'ahadkins5@who.int'),
('Taller Río Negro', 'histats.com', 'ckopisch6@opensource.org'),
('Taller Anaco', 'intel.com', 'aatkins7@icq.com'),
('Taller Aragua', 'springer.com', 'nsenn8@yellowbook.com'),
('Taller Manuel Ezequiel Bruzual', 'mail.ru', 'todrought9@sbwire.com'),
('Taller Diego Bautista Urbaneja', 'wikispaces.com', 'dbencka@1688.com'),
('Taller Fernando Peñalver', 'hugedomains.com', 'cwortonb@gmpg.org'),
('Taller Francisco Del Carmen Carvajal', 'hao123.com', 'sbailliec@free.fr'),
('Taller General Sir Arthur McGregor', 'histats.com', 'askinleyd@lycos.com'),
('Taller Guanta', 'upenn.edu', 'cmccombe@fotki.com'),
('Taller Independencia', 'elegantthemes.com', 'jparsonsf@oracle.com'),
('Taller José Gregorio Monagas', 'mashable.com', 'agerardetg@mapquest.com'),
('Taller Juan Antonio Sotillo', 'si.edu', 'hdantonih@feedburner.com'),
('Taller Juan Manuel Cajigal', 'jalbum.net', 'cloidli@nasa.gov'),
('Taller Libertad', 'bizjournals.com', 'oextilj@goo.ne.jp'),
('Taller Francisco de Miranda', 'alibaba.com', 'ypaulackk@virginia.edu'),
('Taller Pedro María Freites', 'princeton.edu', 'bslyml@xinhuanet.com'),
('Taller Píritu', 'simplemachines.org', 'dlinwoodm@sbwire.com'),
('Taller San José de Guanipa', 'webnode.com', 'nnorthagen@livejournal.com'),
('Taller San Juan de Capistrano', 'cocolog-nifty.com', 'dahlfo@topsy.com'),
('Taller Santa Ana', 'china.com.cn', 'iandrinp@technorati.com'),
('Taller Simón Bolívar', 'microsoft.com', 'mfrenchumq@prnewswire.com'),
('Taller Simón Rodríguez', 'merriam-webster.com', 'jgraemer@wordpress.org'),
('Taller Achaguas', 'buzzfeed.com', 'dlaurands@myspace.com'),
('Taller Biruaca', 'symantec.com', 'mbranigant@1und1.de'),
('Taller Muñóz', 'canalblog.com', 'bborthu@skype.com'),
('Taller Páez', 'seattletimes.com', 'jcumberv@slideshare.net'),
('Taller Pedro Camejo', 'comsenz.com', 'kcoynew@admin.ch'),
('Taller Rómulo Gallegos', 'bbc.co.uk', 'amcdermotx@adobe.com'),
('Taller San Fernando', 'google.nl', 'dnorhenyy@sohu.com'),
('Taller Atanasio Girardot', 'merriam-webster.com', 'pkoubekz@gnu.org'),
('Taller Bolívar', 'springer.com', 'jhaddinton10@ucoz.ru'),
('Taller Camatagua', 'quantcast.com', 'tmussard11@paginegialle.it'),
('Taller Francisco Linares Alcántara', 'oaic.gov.au', 'rwythill12@booking.com'),
('Taller José Ángel Lamas', 'uiuc.edu', 'zmcgriele13@nydailynews.com'),
('Taller José Félix Ribas', 'imdb.com', 'myurkov14@imgur.com'),
('Taller José Rafael Revenga', 'ask.com', 'zlidyard15@sfgate.com'),
('Taller Libertador', 'yellowbook.com', 'dhorning16@hud.gov'),
('Taller Mario Briceño Iragorry', 'prlog.org', 'jskoof17@dyndns.org'),
('Taller Ocumare de la Costa de Oro', 'harvard.edu', 'gberriman18@phpbb.com'),
('Taller San Casimiro', 'businessweek.com', 'btowhey19@last.fm'),
('Taller San Sebastián', 'liveinternet.ru', 'ehanmer1a@hostgator.com'),
('Taller Santiago Mariño', 'google.es', 'mcalderhead1b@hud.gov'),
('Taller Santos Michelena', 'imageshack.us', 'phugonet1c@rambler.ru'),
('Taller Sucre', 'instagram.com', 'dpreuvost1d@twitter.com'),
('Taller Tovar', 'google.nl', 'jthrelkeld1e@bbc.co.uk'),
('Taller Urdaneta', 'ameblo.jp', 'dvossgen1f@washington.edu'),
('Taller Zamora', 'cisco.com', 'tkulicke1g@dyndns.org'),
('Taller Alberto Arvelo Torrealba', 'qq.com', 'kbundock1h@seattletimes.com'),
('Taller Andrés Eloy Blanco', 'smugmug.com', 'nturnock1i@live.com'),
('Taller Antonio José de Sucre', 'ihg.com', 'ssturmey1j@yellowpages.com'),
('Taller Arismendi', 'bluehost.com', 'cdenman1k@bravesites.com'),
('Taller Barinas', '360.cn', 'amcgibbon1l@patch.com'),
('Taller Bolívar', 'ucsd.edu', 'kclere1m@furl.net'),
('Taller Cruz Paredes', 't.co', 'jcullerne1n@hubpages.com'),
('Taller Ezequiel Zamora', 'ucoz.com', 'efishly1o@youku.com'),
('Taller Obispos', 'domainmarket.com', 'atruwert1p@sphinn.com'),
('Taller Pedraza', 'paypal.com', 'idowell1q@cisco.com'),
('Taller Rojas', 'cloudflare.com', 'arobichon1r@washington.edu'),
('Taller Sosa', 'eepurl.com', 'gmeenan1s@exblog.jp'),
('Taller Caroní', 'epa.gov', 'sbulger1t@merriam-webster.com'),
('Taller Cedeño', 'psu.edu', 'ggeane1u@google.fr'),
('Taller El Callao', 'issuu.com', 'elaurie1v@chicagotribune.com'),
('Taller Gran Sabana', 'imdb.com', 'wdax1w@topsy.com'),
('Taller Heres', 'icq.com', 'jcookney1x@seesaa.net'),
('Taller Piar', 'ustream.tv', 'snussen1y@sphinn.com'),
('Taller Angostura (Raúl Leoni)', 'artisteer.com', 'sgabriel1z@washingtonpost.com'),
('Taller Roscio', 'tuttocitta.it', 'ldomenc20@stanford.edu'),
('Taller Sifontes', 'house.gov', 'glomaz21@ucoz.ru'),
('Taller Sucre', 'youtu.be', 'asaffell22@live.com'),
('Taller Padre Pedro Chien', 'sitemeter.com', 'hsyred23@un.org'),
('Taller Bejuma', 'paginegialle.it', 'spockey24@rambler.ru'),
('Taller Carlos Arvelo', 'fotki.com', 'mfinding25@goodreads.com'),
('Taller Diego Ibarra', 'youku.com', 'rrudram26@imgur.com'),
('Taller Guacara', 'buzzfeed.com', 'sedmands27@php.net'),
('Taller Juan José Mora', 'example.com', 'gbernakiewicz28@cdbaby.com'),
('Taller Libertador', 'archive.org', 'gpadwick29@blogger.com'),
('Taller Los Guayos', 'last.fm', 'bcaskie2a@instagram.com'),
('Taller Miranda', 'biglobe.ne.jp', 'jhugett2b@wordpress.org'),
('Taller Montalbán', 'elegantthemes.com', 'kserman2c@tripod.com'),
('Taller Naguanagua', 'infoseek.co.jp', 'lnutbean2d@boston.com'),
('Taller Puerto Cabello', 'hhs.gov', 'yhuggen2e@etsy.com'),
('Taller San Diego', 'comsenz.com', 'jmyall2f@ovh.net'),
('Taller San Joaquín', 'imageshack.us', 'abickford2g@123-reg.co.uk'),
('Taller Valencia', 'aol.com', 'lpoundsford2h@ted.com'),
('Taller Anzoátegui', 'cafepress.com', 'kbruyntjes2i@tamu.edu'),
('Taller Tinaquillo', 'washingtonpost.com', 'tstenners2j@aboutads.info'),
('Taller Girardot', 'amazon.co.jp', 'xmackenney2k@pinterest.com'),
('Taller Lima Blanco', 'feedburner.com', 'wmarch2l@cocolog-nifty.com'),
('Taller Pao de San Juan Bautista', 'wired.com', 'umeardon2m@china.com.cn'),
('Taller Ricaurte', 'forbes.com', 'cderuggiero2n@berkeley.edu'),
('Taller Rómulo Gallegos', 'icq.com', 'ibiskup2o@bluehost.com'),
('Taller San Carlos', 'sourceforge.net', 'astollhofer2p@epa.gov'),
('Taller Tinaco', 'admin.ch', 'lmorrid2q@prweb.com'),
('Taller Antonio Díaz', 'prlog.org', 'lmartellini2r@symantec.com'),
('Taller Casacoima', 'symantec.com', 'calywin2s@youtu.be'),
('Taller Pedernales', 'buzzfeed.com', 'smcphilip2t@tripadvisor.com'),
('Taller Tucupita', 'yandex.ru', 'idowden2u@buzzfeed.com'),
('Taller Acosta', 'trellian.com', 'lfeirn2v@cmu.edu'),
('Taller Bolívar', 'blogger.com', 'lhulcoop2w@apache.org'),
('Taller Buchivacoa', 'blinklist.com', 'mstollwerck2x@rambler.ru'),
('Taller Cacique Manaure', 'unblog.fr', 'aramey2y@tamu.edu'),
('Taller Carirubana', 'google.ru', 'lwadlow2z@utexas.edu'),
('Taller Colina', 'google.ru', 'ebraddock30@pagesperso-orange.fr'),
('Taller Dabajuro', 'ftc.gov', 'mmoubray31@ucoz.ru'),
('Taller Democracia', 'apple.com', 'fgerlack32@amazon.co.jp'),
('Taller Falcón', 'symantec.com', 'hsaltman33@github.com'),
('Taller Federación', 'netvibes.com', 'fheiss34@clickbank.net'),
('Taller Jacura', 'oaic.gov.au', 'lkilbourn35@typepad.com'),
('Taller José Laurencio Silva', 'flickr.com', 'wfarrimond36@illinois.edu'),
('Taller Los Taques', 'meetup.com', 'ukesteven37@tmall.com'),
('Taller Mauroa', 'telegraph.co.uk', 'lcess38@ox.ac.uk'),
('Taller Miranda', 'hibu.com', 'tseed39@exblog.jp'),
('Taller Monseñor Iturriza', 'un.org', 'kensor3a@weebly.com'),
('Taller Palmasola', 'about.me', 'eburker3b@uol.com.br'),
('Taller Petit', 'jalbum.net', 'schildes3c@si.edu'),
('Taller Píritu', 'mayoclinic.com', 'cdacosta3d@phoca.cz'),
('Taller San Francisco', 'smugmug.com', 'jweond3e@shutterfly.com'),
('Taller Sucre', 'gnu.org', 'mbourthouloume3f@purevolume.com'),
('Taller Tocópero', 'google.cn', 'hgunthorpe3g@xing.com'),
('Taller Unión', 'google.com', 'lpetel3h@google.ru'),
('Taller Urumaco', 'plala.or.jp', 'rwahner3i@google.fr'),
('Taller Zamora', 'digg.com', 'bwaistell3j@deliciousdays.com'),
('Taller Camaguán', 'eventbrite.com', 'dlangton3k@fda.gov'),
('Taller Chaguaramas', 'nps.gov', 'pbram3l@networkadvertising.org'),
('Taller El Socorro', 'aboutads.info', 'shinnerk3m@dot.gov'),
('Taller José Félix Ribas', 'google.cn', 'ccessford3n@joomla.org'),
('Taller José Tadeo Monagas', 'cloudflare.com', 'ggiraux3o@omniture.com'),
('Taller Juan Germán Roscio', 'last.fm', 'cwinchcombe3p@jiathis.com'),
('Taller Julián Mellado', 'nsw.gov.au', 'wreven3q@icq.com'),
('Taller Las Mercedes', 'ehow.com', 'rimm3r@pinterest.com'),
('Taller Leonardo Infante', 'over-blog.com', 'msutherley3s@huffingtonpost.com'),
('Taller Pedro Zaraza', 'pinterest.com', 'bolander3t@ft.com'),
('Taller Ortíz', 'dagondesign.com', 'bsparrow3u@harvard.edu'),
('Taller San Gerónimo de Guayabal', 'cloudflare.com', 'sbeaten3v@epa.gov'),
('Taller San José de Guaribe', 'cam.ac.uk', 'sdannell3w@mapy.cz'),
('Taller Santa María de Ipire', 'independent.co.uk', 'mstonall3x@posterous.com'),
('Taller Sebastián Francisco de Miranda', 'indiatimes.com', 'vmarien3y@yahoo.co.jp'),
('Taller Andrés Eloy Blanco', 'quantcast.com', 'lbram3z@answers.com'),
('Taller Crespo', 'walmart.com', 'cewbanck40@washington.edu'),
('Taller Iribarren', 'webnode.com', 'bsellers41@freewebs.com'),
('Taller Jiménez', 'cloudflare.com', 'dbackshaw42@moonfruit.com'),
('Taller Morán', 'samsung.com', 'dskypp43@bigcartel.com'),
('Taller Palavecino', 'sfgate.com', 'dclemoes44@myspace.com'),
('Taller Simón Planas', 'tiny.cc', 'bbrussell45@elegantthemes.com'),
('Taller Torres', 'woothemes.com', 'dsperling46@reference.com'),
('Taller Urdaneta', 'dropbox.com', 'mfilkin47@livejournal.com'),
('Taller Alberto Adriani', 'theguardian.com', 'oespinheira48@upenn.edu'),
('Taller Andrés Bello', 'umn.edu', 'jchattoe49@google.com'),
('Taller Antonio Pinto Salinas', 'ifeng.com', 'cmarns4a@yellowbook.com'),
('Taller Aricagua', 'bandcamp.com', 'scaban4b@over-blog.com'),
('Taller Arzobispo Chacón', 'fotki.com', 'amumbey4c@house.gov'),
('Taller Campo Elías', 'ucsd.edu', 'rphethean4d@timesonline.co.uk'),
('Taller Caracciolo Parra Olmedo', 'jiathis.com', 'lhumpherston4e@zdnet.com'),
('Taller Cardenal Quintero', 'irs.gov', 'bpauletto4f@domainmarket.com'),
('Taller Guaraque', 'liveinternet.ru', 'sstallibrass4g@paypal.com'),
('Taller Julio César Salas', 'auda.org.au', 'tsyred4h@wikia.com'),
('Taller Justo Briceño', 'boston.com', 'bomullaney4i@oakley.com'),
('Taller Libertador', 'google.de', 'rshackleton4j@weather.com'),
('Taller Miranda', 'scribd.com', 'tmollett4k@cnn.com'),
('Taller Obispo Ramos de Lora', 'hud.gov', 'glevecque4l@ucoz.com'),
('Taller Padre Noguera', 'youtube.com', 'lbarents4m@tripadvisor.com'),
('Taller Pueblo Llano', 'about.com', 'gwaugh4n@goo.gl'),
('Taller Rangel', 'pagesperso-orange.fr', 'mpasmore4o@xrea.com'),
('Taller Rivas Dávila', 'cdc.gov', 'hverbeek4p@ucsd.edu'),
('Taller Santos Marquina', 'cnbc.com', 'jmarkovic4q@pinterest.com'),
('Taller Sucre', 'opensource.org', 'mcluer4r@opera.com'),
('Taller Tovar', 'acquirethisname.com', 'snovichenko4s@yellowpages.com'),
('Taller Tulio Febres Cordero', 'eventbrite.com', 'tmaseyk4t@nifty.com'),
('Taller Zea', 'wikimedia.org', 'rkinsell4u@yandex.ru'),
('Taller Acevedo', 'blogtalkradio.com', 'grawle4v@netvibes.com'),
('Taller Andrés Bello', 'nationalgeographic.com', 'bfilde4w@uol.com.br'),
('Taller Baruta', 'alexa.com', 'rkach4x@webs.com'),
('Taller Brión', 'walmart.com', 'rstamper4y@ftc.gov'),
('Taller Buroz', 'cam.ac.uk', 'bdatte4z@nyu.edu'),
('Taller Carrizal', 'bandcamp.com', 'aflood50@nps.gov'),
('Taller Chacao', 'drupal.org', 'rmcgavin51@disqus.com'),
('Taller Cristóbal Rojas', 'sciencedirect.com', 'mstrickler52@trellian.com'),
('Taller El Hatillo', 'etsy.com', 'cborleace53@cdc.gov'),
('Taller Guaicaipuro', 'ustream.tv', 'skynsey54@ox.ac.uk'),
('Taller Independencia', 'hugedomains.com', 'awallentin55@earthlink.net'),
('Taller Lander', 'delicious.com', 'rlippatt56@spiegel.de'),
('Taller Los Salias', 'blogspot.com', 'jdibernardo57@netscape.com'),
('Taller Páez', 'springer.com', 'swickey58@odnoklassniki.ru'),
('Taller Paz Castillo', 'creativecommons.org', 'jwiddowfield59@auda.org.au'),
('Taller Pedro Gual', 'businessinsider.com', 'kscobbie5a@indiatimes.com'),
('Taller Plaza', 'github.com', 'lscadding5b@theglobeandmail.com'),
('Taller Simón Bolívar', 'howstuffworks.com', 'msperring5c@yellowbook.com'),
('Taller Sucre', 'blogs.com', 'shague5d@unicef.org'),
('Taller Urdaneta', 'gravatar.com', 'wgeorgel5e@myspace.com'),
('Taller Zamora', 'ucoz.com', 'jtarborn5f@smugmug.com'),
('Taller Acosta', 'so-net.ne.jp', 'maymer5g@ed.gov'),
('Taller Aguasay', 'devhub.com', 'abullocke5h@java.com'),
('Taller Bolívar', 'miibeian.gov.cn', 'ppatis5i@independent.co.uk'),
('Taller Caripe', 'java.com', 'mbaudone5j@discuz.net'),
('Taller Cedeño', 'ebay.com', 'gdougherty5k@hp.com'),
('Taller Ezequiel Zamora', 'uol.com.br', 'rroffey5l@un.org'),
('Taller Libertador', 'gov.uk', 'oyair5m@purevolume.com'),
('Taller Maturín', '360.cn', 'jbyrkmyr5n@dell.com'),
('Taller Piar', 'ezinearticles.com', 'hgoss5o@last.fm'),
('Taller Punceres', 'flavors.me', 'pwike5p@amazon.com'),
('Taller Santa Bárbara', 'plala.or.jp', 'pwarham5q@shop-pro.jp'),
('Taller Sotillo', 'stumbleupon.com', 'hwalmsley5r@japanpost.jp'),
('Taller Uracoa', 'sciencedirect.com', 'blarwell5s@google.pl'),
('Taller Antolín del Campo', 'imgur.com', 'agrinnov5t@lycos.com'),
('Taller Arismendi', '51.la', 'ttidmarsh5u@list-manage.com'),
('Taller García', 'csmonitor.com', 'tswitland5v@google.com.br'),
('Taller Gómez', 'woothemes.com', 'ngrogor5w@opera.com'),
('Taller Maneiro', 'php.net', 'stoderi5x@vk.com'),
('Taller Marcano', 'etsy.com', 'rdarragon5y@springer.com'),
('Taller Mariño', 'forbes.com', 'eyouell5z@narod.ru'),
('Taller Península de Macanao', 'mashable.com', 'blitchfield60@ebay.com'),
('Taller Tubores', 'statcounter.com', 'lkellogg61@indiatimes.com'),
('Taller Villalba', 't.co', 'rsachno62@hatena.ne.jp'),
('Taller Díaz', 'paypal.com', 'ldrillingcourt63@newsvine.com'),
('Taller Agua Blanca', 'pcworld.com', 'mgrene64@mediafire.com'),
('Taller Araure', 'google.fr', 'jchallender65@amazon.co.uk'),
('Taller Esteller', 'liveinternet.ru', 'cboone66@weather.com'),
('Taller Guanare', 'jugem.jp', 'bbothams67@techcrunch.com'),
('Taller Guanarito', 'devhub.com', 'wjubert68@wisc.edu'),
('Taller Monseñor José Vicente de Unda', 'printfriendly.com', 'vkhrishtafovich69@godaddy.com'),
('Taller Ospino', 'reuters.com', 'sohanley6a@fema.gov'),
('Taller Páez', 'mapquest.com', 'vmartensen6b@google.fr'),
('Taller Papelón', 'google.com.au', 'tnote6c@yale.edu'),
('Taller San Genaro de Boconoíto', 'marriott.com', 'nsunderland6d@about.com'),
('Taller San Rafael de Onoto', 'bizjournals.com', 'bsaggs6e@google.de'),
('Taller Santa Rosalía', 'ucoz.com', 'gvanson6f@webeden.co.uk'),
('Taller Sucre', 'ucla.edu', 'mwickie6g@studiopress.com'),
('Taller Turén', 'fc2.com', 'lkrysztofowicz6h@a8.net'),
('Taller Andrés Eloy Blanco', 'sbwire.com', 'bhafford6i@microsoft.com'),
('Taller Andrés Mata', 'ft.com', 'aantrack6j@amazonaws.com'),
('Taller Arismendi', 'psu.edu', 'nprettyjohns6k@cbc.ca'),
('Taller Benítez', 'arizona.edu', 'htreece6l@nba.com'),
('Taller Bermúdez', 'reddit.com', 'etremlett6m@nasa.gov'),
('Taller Bolívar', 'spotify.com', 'csinnie6n@prlog.org'),
('Taller Cajigal', 'boston.com', 'tlemon6o@csmonitor.com'),
('Taller Cruz Salmerón Acosta', 'admin.ch', 'trowen6p@wiley.com'),
('Taller Libertador', 'sourceforge.net', 'mpaolotto6q@cpanel.net'),
('Taller Mariño', 'slideshare.net', 'amasedon6r@mail.ru'),
('Taller Mejía', 'reddit.com', 'dmoffat6s@tinypic.com'),
('Taller Montes', 'princeton.edu', 'sdelany6t@mail.ru'),
('Taller Ribero', 'addtoany.com', 'cvickers6u@about.me'),
('Taller Sucre', 'hibu.com', 'rdivill6v@skype.com'),
('Taller Valdéz', 'woothemes.com', 'fbrafield6w@gov.uk'),
('Taller Andrés Bello', 'histats.com', 'gowen6x@census.gov'),
('Taller Antonio Rómulo Costa', 'umn.edu', 'xmalthouse6y@diigo.com'),
('Taller Ayacucho', 'wunderground.com', 'etennewell6z@mail.ru'),
('Taller Bolívar', 'ocn.ne.jp', 'sredemile70@symantec.com'),
('Taller Cárdenas', 'nyu.edu', 'mvel71@un.org'),
('Taller Córdoba', 'infoseek.co.jp', 'ljeary72@nyu.edu'),
('Taller Fernández Feo', 'bing.com', 'hpurrington73@nps.gov'),
('Taller Francisco de Miranda', 'ocn.ne.jp', 'dfozard74@smh.com.au'),
('Taller García de Hevia', 'cnn.com', 'gdowber75@weebly.com'),
('Taller Guásimos', 'vinaora.com', 'lradolf76@shutterfly.com'),
('Taller Independencia', 'java.com', 'cmassinger77@sphinn.com'),
('Taller Jáuregui', 'shutterfly.com', 'cweakley78@scribd.com'),
('Taller José María Vargas', 'si.edu', 'hmorgen79@rambler.ru'),
('Taller Junín', 'cornell.edu', 'nlindup7a@marriott.com'),
('Taller Libertad', 'domainmarket.com', 'dteodoro7b@flavors.me'),
('Taller Libertador', 'si.edu', 'asara7c@google.cn'),
('Taller Lobatera', 'furl.net', 'focooney7d@github.io'),
('Taller Michelena', 'independent.co.uk', 'cmardall7e@dailymail.co.uk'),
('Taller Panamericano', 'unblog.fr', 'tklessmann7f@china.com.cn'),
('Taller Pedro María Ureña', 'theglobeandmail.com', 'sblakelock7g@mlb.com'),
('Taller Rafael Urdaneta', 'technorati.com', 'dshepherdson7h@craigslist.org'),
('Taller Samuel Darío Maldonado', 'rediff.com', 'vplak7i@mozilla.org'),
('Taller San Cristóbal', 'nasa.gov', 'cluscombe7j@ucoz.ru'),
('Taller Seboruco', 'youtube.com', 'wlorryman7k@cpanel.net'),
('Taller Simón Rodríguez', 'cdbaby.com', 'rspellacy7l@soundcloud.com'),
('Taller Sucre', 'cnet.com', 'pwrighton7m@wp.com'),
('Taller Torbes', 'mozilla.org', 'bfearnill7n@umich.edu'),
('Taller Uribante', 'answers.com', 'ajindra7o@time.com'),
('Taller San Judas Tadeo', 'i2i.jp', 'wmucklo7p@bluehost.com'),
('Taller Andrés Bello', 'nba.com', 'scoumbe7q@1und1.de'),
('Taller Boconó', 'instagram.com', 'koronan7r@behance.net'),
('Taller Bolívar', 'istockphoto.com', 'idur7s@fda.gov'),
('Taller Candelaria', 'comcast.net', 'rdaykin7t@unesco.org'),
('Taller Carache', 'tinyurl.com', 'aellyatt7u@google.fr'),
('Taller Escuque', 'wordpress.org', 'lflanigan7v@i2i.jp'),
('Taller José Felipe Márquez Cañizalez', 'tamu.edu', 'ariccardelli7w@phoca.cz'),
('Taller Juan Vicente Campos Elías', 'joomla.org', 'ademitri7x@upenn.edu'),
('Taller La Ceiba', 'google.ru', 'mcapstick7y@comsenz.com'),
('Taller Miranda', 'berkeley.edu', 'smellor7z@netscape.com'),
('Taller Monte Carmelo', 'shinystat.com', 'achave80@washington.edu'),
('Taller Motatán', 'thetimes.co.uk', 'tfyall81@gravatar.com'),
('Taller Pampán', 'so-net.ne.jp', 'cdalli82@blinklist.com'),
('Taller Pampanito', 'cam.ac.uk', 'pkinworthy83@artisteer.com'),
('Taller Rafael Rangel', 'cdc.gov', 'mdomelow84@un.org'),
('Taller San Rafael de Carvajal', 'epa.gov', 'crene85@people.com.cn'),
('Taller Sucre', 'digg.com', 'escholes86@yale.edu'),
('Taller Trujillo', 'yahoo.co.jp', 'mlawling87@rakuten.co.jp'),
('Taller Urdaneta', '1688.com', 'gsafell88@nsw.gov.au'),
('Taller Valera', 'github.com', 'whawes89@zdnet.com'),
('Taller Vargas', 'latimes.com', 'gomarkey8a@deliciousdays.com'),
('Taller Arístides Bastidas', 'paginegialle.it', 'sclarycott8b@chicagotribune.com'),
('Taller Bolívar', 'tuttocitta.it', 'cpeterken8c@ycombinator.com'),
('Taller Bruzual', 'yale.edu', 'gpentony8d@ftc.gov'),
('Taller Cocorote', 'omniture.com', 'mgiacopetti8e@tinyurl.com'),
('Taller Independencia', 'wp.com', 'lcamilio8f@sciencedaily.com'),
('Taller José Antonio Páez', 'pbs.org', 'rcawthra8g@census.gov'),
('Taller La Trinidad', 'chronoengine.com', 'jgaythwaite8h@google.ru'),
('Taller Manuel Monge', 'theguardian.com', 'fgurry8i@about.me'),
('Taller Nirgua', 'usda.gov', 'cbilsford8j@smugmug.com'),
('Taller Peña', 'cafepress.com', 'pshires8k@miitbeian.gov.cn'),
('Taller San Felipe', 'sciencedaily.com', 'cdows8l@weebly.com'),
('Taller Sucre', 'vistaprint.com', 'dskirvin8m@cbsnews.com'),
('Taller Urachiche', 'apache.org', 'cleckey8n@xing.com'),
('Taller José Joaquín Veroes', 'smugmug.com', 'gzellner8o@toplist.cz'),
('Taller Almirante Padilla', 'usgs.gov', 'lparman8p@prnewswire.com'),
('Taller Baralt', 'macromedia.com', 'agerlts8q@barnesandnoble.com'),
('Taller Cabimas', 'ibm.com', 'bargo8r@utexas.edu'),
('Taller Catatumbo', 'jimdo.com', 'einder8s@wix.com'),
('Taller Colón', 'multiply.com', 'rabrahmer8t@sphinn.com'),
('Taller Francisco Javier Pulgar', 'goo.ne.jp', 'hdanaher8u@freewebs.com'),
('Taller Páez', 'nasa.gov', 'zakroyd8v@imgur.com'),
('Taller Jesús Enrique Losada', 'umich.edu', 'bdeclerq8w@homestead.com'),
('Taller Jesús María Semprún', 'elegantthemes.com', 'jprozillo8x@live.com'),
('Taller La Cañada de Urdaneta', 'jigsy.com', 'swarrier8y@technorati.com'),
('Taller Lagunillas', 'amazon.co.jp', 'skirkness8z@netvibes.com'),
('Taller Machiques de Perijá', 'stanford.edu', 'aabrahams90@mit.edu'),
('Taller Mara', 'yahoo.co.jp', 'gkaminski91@fc2.com'),
('Taller Maracaibo', 'usnews.com', 'ssharnock92@google.ca'),
('Taller Miranda', 'xing.com', 'bdickerson93@myspace.com'),
('Taller Rosario de Perijá', 'noaa.gov', 'mhurich94@github.com'),
('Taller San Francisco', 'sbwire.com', 'lbreacher95@nba.com'),
('Taller Santa Rita', 'buzzfeed.com', 'dskellern96@shutterfly.com'),
('Taller Simón Bolívar', 'mozilla.org', 'twinny97@home.pl'),
('Taller Sucre', 'telegraph.co.uk', 'bgame98@prlog.org'),
('Taller Valmore Rodríguez', 'constantcontact.com', 'nbeeching99@marriott.com'),
('Taller Libertador', 'indiegogo.com', 'fgynne9a@disqus.com');
